application: gameeonerp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css
  
- url: /font-awesome
  static_dir: font-awesome 
 
- url: /fonts
  static_dir: fonts
  
- url: /img
  static_dir: img
  
- url: /extra
  static_dir: extra

- url: /assets
  static_dir: assets  
 
- url: /less
  static_dir: less
  
- url: /js
  static_dir: js 
  
- url: /lineicons
  static_dir: lineicons 
  
- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"
  
- name: webapp2
  version: "2.5.2"
